name: Pre-merge integration test
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  deploy:
    name: pre-merge-integration-tests
    runs-on: ubuntu-latest
    environment: di-ipv-cri-dl-dev-admin
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
      STACK_NAME_PREFIX: pre-merge-integration
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DL_DEV_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM build
        run: sam build -t infrastructure/lambda/template.yaml

      - name: Set short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: SAM deploy integration test stack
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          aws ssm put-parameter --name "/${STACK_NAME}/contraindicationMappings" --type "String" --value "${{ secrets.SENSTIVE_PARAM_CI_MAPPINGS }}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/dcsEndpoint" --type "String" --value "${{ secrets.SENSTIVE_PARAM_DCS_ENDPOINT }}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/encryptionCertForDrivingPermitToEncrypt" --type "String" --value "${{ secrets.SENSTIVE_PARAM_ENCRYPTION_FOR_DRIVING_PERMIT_TO_ENCRYPT }}" 2>&1 > /dev/null     
          aws ssm put-parameter --name "/${STACK_NAME}/signingCertForDcsToVerify" --type "String" --value "${{ secrets.SENSTIVE_PARAM_SIGNING_CERT_FOR_DCS_TO_VERIFY }}" 2>&1 > /dev/null               
          aws ssm put-parameter --name "/${STACK_NAME}/signingCertForDrivingPermitToVerify" --type "String" --value "${{ secrets.SENSTIVE_PARAM_SIGNING_CERT_FOR_DRIVING_PERMIT_TO_VERIFY }}" 2>&1 > /dev/null                              
          aws ssm put-parameter --name "/${STACK_NAME}/signingKeyForDrivingPermitToSign" --type "String" --value "${{ secrets.SENSTIVE_PARAM_SIGNING_KEY_FOR_DRIVING_PERMIT_TO_SIGN }}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/tlsCert" --type "String" --value "${{ secrets.SENSTIVE_PARAM_TLS_CERT }}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/tlsIntermediateCertificate" --type "String" --value "${{ secrets.SENSTIVE_PARAM_TLS_INTERMEDIATE_CERTIFICATE}}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/tlsKey" --type "String" --value "${{ secrets.SENSTIVE_PARAM_TLS_KEY}}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/tlsRootCertificate" --type "String" --value "${{ secrets.SENSTIVE_PARAM_TLS_ROOT_CERTIFICATE}}" 2>&1 > /dev/null
          aws ssm put-parameter --name "/${STACK_NAME}/encryptionKeyForDrivingPermitToDecrypt" --type "String" --value "${{ secrets.SENSTIVE_PARAM_ENCRYPTION_KEY_FOR_DRIVING_PERMIT_TO_DECRYPT}}" 2>&1 > /dev/null                                                                        
          sam deploy \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --parameter-overrides "Environment=${{ env.ENVIRONMENT }} CodeSigningEnabled=false AuditEventNamePrefix=/common-cri-parameters/AuditEventNamePrefix CriIdentifier=/common-cri-parameters/CriIdentifier CommonStackName=common-cri-api" \
            --stack-name $STACK_NAME \
            --s3-bucket ${{ secrets.AWS_DL_DEV_CONFIG_BUCKET }} \
            --s3-prefix $STACK_NAME \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM

      - name: Run API integration tests
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          BROWSER: chrome-headless
          APIGW_API_KEY: ${{ secrets.API_KEY_CRI_DL_DEV }}
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
        run: |
          echo "🤞 now run integration tests..."
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          API_GATEWAY_ID_PRIVATE=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "PrivateDrivingPermitApiGatewayId").OutputValue')
          API_GATEWAY_ID_PUBLIC=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "PublicDrivingPermitApiGatewayId").OutputValue')
          export API_GATEWAY_ID_PRIVATE=$API_GATEWAY_ID_PRIVATE
          export API_GATEWAY_ID_PUBLIC=$API_GATEWAY_ID_PUBLIC
          cd acceptance-tests && ./gradlew clean cucumber -P tags=@pre-merge

      - name: Delete integration test stack
        if: always()
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          aws ssm delete-parameter --name "/${STACK_NAME}/contraindicationMappings" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/dcsEndpoint" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/encryptionCertForDrivingPermitToEncrypt" 2>&1 > /dev/null     
          aws ssm delete-parameter --name "/${STACK_NAME}/signingCertForDcsToVerify" 2>&1 > /dev/null               
          aws ssm delete-parameter --name "/${STACK_NAME}/signingCertForDrivingPermitToVerify" 2>&1 > /dev/null                              
          aws ssm delete-parameter --name "/${STACK_NAME}/signingKeyForDrivingPermitToSign" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/tlsCert" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/tlsIntermediateCertificate" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/tlsKey" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/tlsRootCertificate" 2>&1 > /dev/null
          aws ssm delete-parameter --name "/${STACK_NAME}/encryptionKeyForDrivingPermitToDecrypt" 2>&1 > /dev/null
          aws cloudformation delete-stack --region ${{ env.AWS_REGION }} --stack-name $STACK_NAME
