name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-sonar-analysis-on-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          ref: 'main'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: 'gradle'
      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Cache Unit Test Reports
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-unit-test-reports-${{ github.sha }}
          path: |
            */build/jacoco/
            */build/reports/
      - name: Run SonarCloud Analysis
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -x test -x spotlessApply -x spotlessCheck
